import React, { createContext, useContext, useState } from 'react';

const translations = {
  EN: {
    brandName: 'වඩු මඩුව',
    brandTag: 'Architectural Carpentry & Timber Works',
    home: 'Home',
    aboutUs: 'About Us',
    aboutHeader: 'Master Carpentry & Architectural Timber Heritage',
    aboutSub: '23+ years of master carpentry excellence in Kalutara, delivering 100% seasoned solid timber doors, windows, staircases, pantry cupboards, door frames and ceilings nationwide.',
    catalog: 'Carpentry Catalog',
    services: 'Services',
    gallery: 'Gallery',
    contact: 'Contact Us',
    customOrder: 'Custom Carpentry Order',
    feedback: 'Client Feedback',
    requestQuote: 'Request Quote',
    adminDesk: 'Admin Desk',
    adminPortal: 'Admin Portal',
    
    // Services List (The 7 actual offerings)
    svcDoors: 'Wooden Doors',
    svcDoorsDesc: 'Bespoke main entrance doors, carved teak doors & bedroom doors.',
    svcWindows: 'Wooden Windows',
    svcWindowsDesc: 'Precision-crafted timber window frames & double glass wooden windows.',
    svcStaircases: 'Staircases & Railings',
    svcStaircasesDesc: 'Solid teak stair steps, handrails & decorative timber balustrades.',
    svcPantry: 'Pantry Cupboards & Kitchen Cabinets',
    svcPantryDesc: 'Custom fitted modular kitchen pantries, cupboards & teak drawers.',
    svcDoorFrames: 'Door Frames (Uluwahu)',
    svcDoorFramesDesc: 'Seasoned Grade-A Teak & Mahogany solid door frames built to last.',
    svcCeilings: 'Wooden Ceilings',
    svcCeilingsDesc: 'Luxury polyurethane polished timber ceiling panels & beam designs.',
    svcGeneralCarpentry: 'General Carpentry Work',
    svcGeneralCarpentryDesc: 'On-site timber installation, repairs, structural woodwork & custom fittings.',

    // Categories
    allCategories: 'All Carpentry Works',
    catDoors: 'Wooden Doors',
    catWindows: 'Wooden Windows',
    catStaircases: 'Staircases',
    catPantry: 'Pantry Cupboards',
    catDoorFrames: 'Door Frames',
    catCeilings: 'Wooden Ceilings',
    catGeneralCarpentry: 'General Carpentry',

    // Hero Slider
    heroBadge1: 'MASTER TIMBER CRAFTSMANSHIP',
    heroTitle1_1: 'Handcrafted Solid Teak',
    heroTitle1_2: 'Main Entrance Doors',
    heroDesc1_1: 'Crafted with over 23 years of master carpentry excellence in Kalutara,',
    heroDesc1_2: 'delivering seasoned Grade-A timber doors built for lifetime durability.',
    heroBadge2: 'FITTED KITCHEN SOLUTIONS',
    heroTitle2_1: 'Custom Modular Teak',
    heroTitle2_2: 'Pantry Cupboard Sets',
    heroDesc2_1: 'Tailored pantry cupboards & kitchen storage crafted from 100% natural wood,',
    heroDesc2_2: 'combining traditional Sri Lankan hand-carving with modern finishes.',
    heroBadge3: 'ARCHITECTURAL WOODWORK',
    heroTitle3_1: 'Precision Staircases &',
    heroTitle3_2: 'Polished Wooden Ceilings',
    heroDesc3_1: 'Bespoke solid wood stair steps, handrails, door frames and ceilings.',
    heroDesc3_2: 'Custom designed to your exact home measurements.',
    heroBadge4: 'FINE TIMBER CARPENTRY',
    heroTitle4_1: 'Premium Handcrafted Woodwork',
    heroTitle4_2: '& Architectural Furniture',
    heroDesc4_1: 'Expertly crafted doors, windows, and custom timber solutions',
    heroDesc4_2: 'designed for long-lasting quality and elegance.',

    // Hero Quick Features
    getStarted: 'Explore Carpentry Catalog',
    customOrderBtn: 'Order Custom Woodwork',
    expYears: '23+ Years',
    expSub: 'Master Carpentry',
    premQuality: '100% Teak',
    premSub: 'Seasoned Timber',
    customMade: 'Custom Fitted',
    customSub: 'To Your Space',
    ontimeDelivery: 'Islandwide',
    ontimeSub: 'Transport & Fitting',

    // Need Something Unique Banner
    needSomethingUnique: 'Need Custom Doors, Windows or Pantry?',
    designIn3D: 'Calculate estimated cost by timber & dimensions instantly',
    designNow: 'Order Custom Woodwork',

    // Catalog Page
    catalogTitle: 'Carpentry Catalog',
    catalogSubtitle: 'Browse our Sri Lankan solid wooden doors, windows, staircases, pantries & ceilings',
    searchPlaceholder: 'Search doors, windows, staircases, pantry, uluwahu, ceiling...',
    sortBy: 'Sort by:',
    priceLowHigh: 'Price: Low to High',
    priceHighLow: 'Price: High to Low',
    nameAZ: 'Name: A to Z',
    categories: 'Categories',
    allProducts: 'All Works',
    noProductsFound: 'No carpentry items matched your search criteria.',
    inStock: 'Available / Custom Order',
    estimatedPrice: 'Estimated Price',
    inquireQuote: 'Inquire / Quote',

    // Services Page
    servicesTitle: 'Our Carpentry & Timber Services',
    servicesSubtitle: 'Master carpentry, doors, windows, pantries, staircases & ceilings by Wadu Maduwa',
    inquireNow: 'Inquire Now',

    // Gallery Page
    galleryTitle: 'Completed Projects Gallery',
    gallerySubtitle: 'Real client installations: doors, windows, staircases, pantry cupboards & ceilings',
    all: 'All',
    view: 'View',
    viewMorePhotos: 'View More Photos',

    // Contact Page
    contactTitle: 'Contact Us',
    contactSubtitle: 'We are here to assist with your custom door, window, pantry & carpentry projects',
    address: 'Workshop Address',
    addressValue: 'Rendapala, Dodangoda, Kalutara, Sri Lanka',
    openInMaps: 'Open in Google Maps',
    phoneWhatsapp: 'Phone / WhatsApp',
    email: 'Email Inquiry',
    workingHours: 'Working Hours',
    workingHoursValue: 'Mon - Sat : 8:00 AM - 6:00 PM',
    sundayClosed: 'Sunday : Closed',
    workshopLocation: 'Workshop Location',
    sendMessage: 'Send Us a Message',
    yourName: 'Your Full Name *',
    phoneNumber: 'Phone Number *',
    emailAddress: 'Email Address',
    projectDetails: 'Carpentry Requirements / Description *',
    submitBtn: 'Submit Inquiry',
    submitting: 'Submitting...',
    messageSentSuccess: 'Thank you! Your inquiry has been sent successfully. We will call you back shortly.',

    // Custom Order Page
    customOrderHeader: 'Order Custom Carpentry Work',
    customOrderSub: 'Select doors, windows, staircases, pantry or ceilings. Choose timber & dimensions for instant price estimates.',
    step1: '1. Select Work Type & Wood',
    step2: '2. Dimensions & Sketches',
    step3: '3. Customer Details & Submit',
    selectFurniture: 'Select Carpentry Work Type',
    selectWood: 'Select Timber Species',
    selectFinish: 'Select Polish Finish',
    setDimensions: 'Dimensions & Measurements',
    lengthCm: 'Height / Length (cm)',
    widthCm: 'Width (cm)',
    heightCm: 'Depth / Thickness (cm)',
    referencePhotos: 'Upload Reference Sketch / Photo',
    uploadPhoto: 'Upload Photo / Sketch',
    remove: 'Remove',
    customerInformation: 'Your Contact & Delivery Details',
    fullName: 'Full Name *',
    addressField: 'Installation Address *',
    districtField: 'District *',
    selectDistrict: 'Select District',
    phoneField: 'Phone Number (WhatsApp) *',
    notesField: 'Special Requirements / Notes',
    estimatedPriceTitle: 'Estimated Guideline Price',
    disclaimerNote: 'Note: This is an estimated guideline price. The final cost will be confirmed after site measurement by our master carpenter.',
    submitOrderWhatsApp: 'Send Order via WhatsApp',
    orderSuccessModalTitle: 'Order Request Sent Successfully!',
    orderSuccessModalSub: 'Your carpentry order details have been sent to our master carpenter via WhatsApp.',
    closeModal: 'Close',

    // Trust & Proof Section
    guaranteedTimberStandard: 'Guaranteed Seasoned Timber',
    whyTrustUsTitle: 'Why 1,200+ Families Trust වඩු මඩුව',
    trustDesc: 'We do not use MDF or cheap composite boards. Every door, window, frame and pantry is crafted from 100% genuine Sri Lankan solid timber.',
    timberGuaranteesTitle: 'Seasoned Timber Guarantees',
    fiveStepProcessTitle: '5-Step Precision Carpentry Workflow',
    step1Title: 'Site Measurements & Idea',
    step1Desc: 'Share your sketch or photo. We take exact site measurements for free.',
    step2Title: 'Grade-A Timber Inspection',
    step2Desc: 'Pick 100% seasoned Teak or Mahogany timber inspected for zero sapwood.',
    step3Title: 'Master Hand-Carving',
    step3Desc: 'Our master craftsmen in Kalutara shape & carve every joint with precision.',
    step4Title: 'PU Lacquer Polish',
    step4Desc: '5-layer protective sanding and polyurethane polish treatment.',
    step5Title: 'On-site Fitting',
    step5Desc: 'Safe transport and professional on-site fitting by our team.',
    clientReviewsTitle: 'What Our Clients Say',

    // Footer
    footerDesc: 'Sri Lanka’s trusted master carpentry workshop. Delivering handcrafted doors, windows, staircases, pantry cupboards & timber ceilings nationwide.',
    quickLinks: 'Quick Links',
    ourServices: 'Our Carpentry Services',
    contactInfo: 'Contact Info',
    allRightsReserved: '© 2026 Wadu Maduwa (වඩු මඩුව). All rights reserved.',
    designedForCraftsmanship: 'Master Carpentry with Pride in Sri Lanka',

    // Feedback Page
    feedbackTitle: 'Client Feedback & Reviews',
    feedbackSubtitle: 'See what clients say about our master carpentry quality and installation service',
    leaveReview: 'Share Your Experience',
    rating: 'Rating',
    submitReview: 'Submit Review',

    // Admin
    adminLoginTitle: 'Admin Portal Login',
    username: 'Username',
    password: 'Password',
    signIn: 'Sign In To Dashboard',
    totalRevenue: 'Total Revenue',
    pendingBalance: 'Pending Balance',
    newInquiries: 'New Inquiries',
    catalogItems: 'Catalogue Items'
  },

  SI: {
    brandName: 'වඩු මඩුව',
    brandTag: 'වඩු කාර්මික සහ දැව නිර්මාණ ශිල්පාගාරය',
    home: 'මුල් පිටුව',
    aboutUs: 'අප ගැන',
    aboutHeader: 'වඩු මඩුව පිළිබඳව',
    aboutSub: 'අවුරුදු 23කට අධික පළපුරුද්ද සහිත කළුතර වඩු මඩුව - පදම් කළ 100% පිරිසිදු තේක්ක, මහෝගනි ලී දොරවල්, ජනෙල්, උළුවහු, පඩිපෙළ, පැන්ට්‍රි කබඩ් සහ ලී සිවිලිම් නිර්මාණය.',
    catalog: 'වඩු කාර්මික ලැයිස්තුව',
    services: 'සේවාවන්',
    gallery: 'ගැලරිය',
    contact: 'සම්බන්ධ වන්න',
    customOrder: 'අභිරුචි ඇණවුම්',
    feedback: 'පාරිභෝගික අදහස්',
    requestQuote: 'මිල ගණන් ලබාගන්න',
    adminDesk: 'ඇඩ්මින් පාලකය',
    adminPortal: 'ඇඩ්මින් පිවිසුම',
    
    // Services List
    svcDoors: 'ලී දොරවල්',
    svcDoorsDesc: 'තේක්ක ප්‍රධාන දොරවල්, කැටයම් දොරවල් සහ කාමර දොරවල්.',
    svcWindows: 'ලී ජනෙල්',
    svcWindowsDesc: 'උසස් ප්‍රමිතියෙන් යුතු ලී ජනෙල් සහ ජනෙල් උළුවහු.',
    svcStaircases: 'ලී පඩිපෙළ සහ අත්වැල',
    svcStaircasesDesc: 'පදම් කළ තේක්ක පඩිපෙළ, අත්වැල සහ ලී ඩිසයින්.',
    svcPantry: 'පැන්ට්‍රි කබඩ් සහ කුස්සිය',
    svcPantryDesc: 'ඔබේ ඉඩකඩට ගැළපෙන නවීන පැන්ට්‍රි කබඩ්.',
    svcDoorFrames: 'දොර උළුවහු',
    svcDoorFramesDesc: '100% පදම් කළ තේක්ක සහ මහෝගනි උළුවහු.',
    svcCeilings: 'ලී සිවිලිම්',
    svcCeilingsDesc: 'අලංකාර ලී සිවිලිම් සහ PU පොලිෂ් නිමාවන්.',
    svcGeneralCarpentry: 'වඩු කාර්මික සේවාවන්',
    svcGeneralCarpentryDesc: 'ස්ථානීය සවිකිරීම්, අලුත්වැඩියා සහ ගොඩනැගිලි ලී වැඩ.',

    // Categories
    allCategories: 'සියලුම වඩු නිර්මාණ',
    catDoors: 'ලී දොරවල්',
    catWindows: 'ලී ජනෙල්',
    catStaircases: 'ලී පඩිපෙළ',
    catPantry: 'පැන්ට්‍රි කබඩ්',
    catDoorFrames: 'දොර උළුවහු',
    catCeilings: 'ලී සිවිලිම්',
    catGeneralCarpentry: 'වඩු කාර්මික සේවාවන්',

    // Hero Slider
    heroBadge1: 'විශිෂ්ට දැව වඩු ශිල්පය',
    heroTitle1_1: 'අතින් නිර්මාණය කළ',
    heroTitle1_2: 'තේක්ක ප්‍රධාන දොරවල්',
    heroDesc1_1: 'අවුරුදු 23කට අධික පළපුරුද්ද සහිත කළුතර වඩු මඩුව,',
    heroDesc1_2: 'පරම්පරා ගණනාවක් පවතින පිරිසිදු තේක්ක දොරවල්.',
    heroBadge2: 'නවීන පැන්ට්‍රි කබඩ්',
    heroTitle2_1: 'ඔබේ නිවසට ගැළපෙන',
    heroTitle2_2: 'පැන්ට්‍රි කබඩ් කට්ටල',
    heroDesc2_1: '100% ස්වාභාවික තේක්ක සහ මහෝගනි ලීයෙන් නිමවන ලද',
    heroDesc2_2: 'කල්පවතින ශ්‍රී ලාංකීය වඩු නිර්මාණ.',
    heroBadge3: 'ගොඩනැගිලි ලී වඩු ශිල්පය',
    heroTitle3_1: 'විශ්වසනීය ලී පඩිපෙළ',
    heroTitle3_2: 'සහ ලී සිවිලිම්',
    heroDesc3_1: 'ඔබේ නිවසේ ඉඩකඩට සහ රුචිකත්වයට ගැළපෙන පරිදි',
    heroDesc3_2: 'අපගේ ශිල්පීන් ලවා සාදාගන්න.',
    heroBadge4: 'උසස් ප්‍රමිතියේ ලී නිර්මාණ',
    heroTitle4_1: 'විශිෂ්ට නිමාවෙන් යුතු',
    heroTitle4_2: 'ලී භාණ්ඩ සහ සේවාවන්',
    heroDesc4_1: 'ඔබේ නිවසට සරිලන පරිදි නිමවන ලද උසස් ලී නිර්මාණ',
    heroDesc4_2: 'කල්පවතින නිමාව සහ විශ්වසනීය සේවාව.',

    // Hero Quick Features
    getStarted: 'ලැයිස්තුව බලන්න',
    customOrderBtn: 'Custom Order',
    expYears: 'අවුරුදු 23+',
    expSub: 'වඩු ශිල්ප පළපුරුද්ද',
    premQuality: '100% තේක්ක',
    premSub: 'පදම් කළ ලී',
    customMade: 'අභිරුචි සවිකිරීම්',
    customSub: 'ඔබගේ ඉඩකඩට',
    ontimeDelivery: 'දිවයින් පුරා',
    ontimeSub: 'ප්‍රවාහනය සහ සවිකිරීම්',

    // Need Something Unique Banner
    needSomethingUnique: 'දොරවල්, ජනෙල් හෝ පැන්ට්‍රි කබඩ් අවශ්‍යද?',
    designIn3D: 'ලී වර්ගය සහ ප්‍රමාණය අනුව දළ මිල ගණන් ලබාගන්න',
    designNow: 'දැන්ම සාදාගන්න',

    // Catalog Page
    catalogTitle: 'වඩු කාර්මික ලැයිස්තුව',
    catalogSubtitle: 'අපගේ තේක්ක දොරවල්, ජනෙල්, උළුවහු, පඩිපෙළ, පැන්ට්‍රි සහ සිවිලිම් පරීක්ෂා කරන්න',
    searchPlaceholder: 'දොරවල්, ජනෙල්, පඩිපෙළ, පැන්ට්‍රි, උළුවහු, සිවිලිම් සොයන්න...',
    sortBy: 'වර්ගීකරණය:',
    priceLowHigh: 'මිල: අඩු සිට වැඩි',
    priceHighLow: 'මිල: වැඩි සිට අඩු',
    nameAZ: 'නම: A සිට Z',
    categories: 'වර්ගීකරණයන්',
    allProducts: 'සියලුම නිර්මාණ',
    noProductsFound: 'ඔබ සොයන නිර්මාණ සොයාගත නොහැකි විය.',
    inStock: 'ඇණවුම් කළ හැක',
    estimatedPrice: 'අනුමාන මිල',
    inquireQuote: 'විමසන්න / Quote',

    // Services Page
    servicesTitle: 'අපගේ වඩු සේවාවන්',
    servicesSubtitle: 'දොරවල්, ජනෙල්, උළුවහු, පඩිපෙළ, පැන්ට්‍රි සහ සිවිලිම් සෑදීමේ වෘත්තීය සේවාවන්',
    inquireNow: 'දැන්ම විමසන්න',

    // Gallery Page
    galleryTitle: 'නිර්මාණ ගැලරිය',
    gallerySubtitle: 'අප විසින් සවිකර දෙන ලද දොරවල්, ජනෙල්, පඩිපෙළ සහ පැන්ට්‍රි කබඩ් ඡායාරූප',
    all: 'සියල්ල',
    view: 'බලන්න',
    viewMorePhotos: 'තවත් ඡායාරූප බලන්න',

    // Contact Page
    contactTitle: 'අප හා සම්බන්ධ වන්න',
    contactSubtitle: 'ඔබගේ සියලු වඩු කාර්මික අවශ්‍යතා සඳහා අප සූදානම්',
    address: 'ලිපිනය',
    addressValue: 'රෙන්ඩපල, දොඩංගොඩ, කළුතර, ශ්‍රී ලංකාව',
    openInMaps: 'Google Maps මගින් බලන්න',
    phoneWhatsapp: 'දුරකථන / WhatsApp',
    email: 'විද්‍යුත් තැපෑල',
    workingHours: 'වැඩකරන වේලාවන්',
    workingHoursValue: 'සඳුදා - සෙනසුරාදා : පෙ.ව 8:00 - ප.ව 6:00',
    sundayClosed: 'ඉරිදා : වසා ඇත',
    workshopLocation: 'වඩු මඩුව පිහිටීම',
    sendMessage: 'පණිවිඩයක් යොමු කරන්න',
    yourName: 'ඔබගේ සම්පූර්ණ නම *',
    phoneNumber: 'දුරකථන අංකය *',
    emailAddress: 'විද්‍යුත් තැපෑල',
    projectDetails: 'අවශ්‍යතාවය / විස්තරය *',
    submitBtn: 'විමසීම යොමු කරන්න',
    submitting: 'යොමු වෙමින් පවතී...',
    messageSentSuccess: 'ස්තූතියි! ඔබගේ විමසීම සාර්ථකව යොමු විය. අපි ළඟදීම ඔබට කථා කරන්නෙමු.',

    // Custom Order Page
    customOrderHeader: 'අභිරුචි වඩු නිර්මාණයකට Order කරන්න',
    customOrderSub: 'දොරවල්, ජනෙල්, පැන්ට්‍රි හෝ සිවිලිම් සඳහා ලී වර්ගය සහ ප්‍රමාණයන් තෝරා දළ මිල ගණන් ගන්න.',
    step1: '1. නිර්මාණය සහ ලී වර්ගය තෝරන්න',
    step2: '2. ප්‍රමාණයන් සහ ඡායාරූප',
    step3: '3. ඔබගේ තොරතුරු සහ යොමු කිරීම',
    selectFurniture: 'වඩු නිර්මාණ වර්ගය තෝරන්න',
    selectWood: 'ලී වර්ගය තෝරන්න',
    selectFinish: 'ලී Finish එක තෝරන්න',
    setDimensions: 'ප්‍රමාණය සහ මැනීම්',
    lengthCm: 'උස / දිග (cm)',
    widthCm: 'පළල (cm)',
    heightCm: 'ගැඹුර / ගනකම (cm)',
    referencePhotos: 'ඡායාරූප / Sketch යොමු කරන්න',
    uploadPhoto: 'ඡායාරූපය එක් කරන්න',
    remove: 'ඉවත් කරන්න',
    customerInformation: 'ඔබගේ තොරතුරු සහ ලිපිනය',
    fullName: 'සම්පූර්ණ නම *',
    addressField: 'ලිපිනය *',
    districtField: 'දිස්ත්‍රික්කය *',
    selectDistrict: 'දිස්ත්‍රික්කය තෝරන්න',
    phoneField: 'දුරකථන අංකය (WhatsApp) *',
    notesField: 'විශේෂ සටහන්',
    estimatedPriceTitle: 'අනුමාන දළ මිල ගණන්',
    disclaimerNote: 'සැලකිය යුතුයි: මෙය දළ තක්සේරු මිලක් පමණි. අවසන් මිල ස්ථානීය මැනීම් පරීක්ෂාවෙන් පසු තීරණය වේ.',
    submitOrderWhatsApp: 'WhatsApp හරහා Order එක යොමු කරන්න',
    orderSuccessModalTitle: 'ඇණවුම සාර්ථකව යොමු විය!',
    orderSuccessModalSub: 'ඔබගේ අභිරුචි වඩු ඇණවුම් විස්තර WhatsApp හරහා අපගේ ශිල්පීන් වෙත යොමු කරන ලදී.',
    closeModal: 'වසා දමන්න',

    // Trust & Proof Section
    guaranteedTimberStandard: 'පිරිසිදු ලී සහතිකය',
    whyTrustUsTitle: '1200+ පාරිභෝගිකයින් වඩු මඩුව විශ්වාස කරන්නේ ඇයි?',
    trustDesc: 'අප MDF හෝ බාල ලෑලි භාවිත නොකරමු. සියලුම දොරවල්, ජනෙල්, උළුවහු සහ පැන්ට්‍රි පදම් කළ 100% ශ්‍රී ලාංකීය ලීයෙන් සාදනු ලැබේ.',
    timberGuaranteesTitle: 'ලී වර්ග සඳහා වගකීම',
    fiveStepProcessTitle: 'වඩු මඩුවේ 5-පියවරේ නිෂ්පාදන ක්‍රියාවලිය',
    step1Title: 'මැනීම් සහ අදහස',
    step1Desc: 'ඔබගේ ඡායාරූපය ලබාදෙන්න. අපි නොමිලේ පැමිණ මැනීම් ලබාගන්නෙමු.',
    step2Title: 'පදම් කළ ලී පරීක්ෂාව',
    step2Desc: 'පදම් කළ 100% Grade-A තේක්ක හෝ මහෝගනි ලී පරීක්ෂා කර තෝරාගන්න.',
    step3Title: 'හස්ත කර්මාන්ත කැටයම්',
    step3Desc: 'කළුතර අපගේ පළපුරුදු වඩු ශිල්පීන් විසින් සියුම් ලෙස නිර්මාණය කරයි.',
    step4Title: 'PU පොලිෂ් නිමාව',
    step4Desc: '5-ස්තර ආරක්ෂිත PU පොලිෂ් සහ මැට්/ග්ලොස් නිමාව.',
    step5Title: 'ස්ථානීය සවිකිරීම්',
    step5Desc: 'දිවයින් පුරා සුරක්ෂිත ප්‍රවාහනය සහ වෘත්තීය සවිකිරීම.',
    clientReviewsTitle: 'පාරිභෝගික අදහස්',

    // Footer
    footerDesc: 'ශ්‍රී ලංකාවේ විශ්වාසනීයම වඩු ශිල්පාගාරය. තේක්ක දොරවල්, ජනෙල්, උළුවහු, පඩිපෙළ, පැන්ට්‍රි සහ ලී සිවිලිම් දිවයින් පුරා.',
    quickLinks: 'ඉක්මන් ලින්ක්',
    ourServices: 'අපගේ වඩු සේවාවන්',
    contactInfo: 'සම්බන්ධතා',
    allRightsReserved: '© 2026 වඩු මඩුව (Wadu Maduwa). සියලුම හිමිකම් ඇවිරිණි.',
    designedForCraftsmanship: 'ශ්‍රී ලාංකීය හස්ත කර්මාන්තයේ අභිමානය',

    // Feedback Page
    feedbackTitle: 'පාරිභෝගික අදහස් සහ ප්‍රතිචාර',
    feedbackSubtitle: 'අපගේ වඩු සේවාව සහ ලී නිමාව පිළිබඳව පාරිභෝගික අත්දැකීම්',
    leaveReview: 'ඔබගේ අදහස පළ කරන්න',
    rating: 'තරු ප්‍රමාණය',
    submitReview: 'යොමු කරන්න',

    // Admin
    adminLoginTitle: 'ඇඩ්මින් පිවිසුම',
    username: 'පරිශීලක නාමය',
    password: 'මුරපදය',
    signIn: 'ඇතුළු වන්න',
    totalRevenue: 'මුළු ආදායම',
    pendingBalance: 'ලැබීමට ඇති මුදල්',
    newInquiries: 'නව විමසීම්',
    catalogItems: 'භාණ්ඩ ප්‍රමාණය'
  },

  TA: {
    brandName: 'வடு மடுவ',
    brandTag: 'தச்சு மற்றும் மரவேலை பட்டறை',
    home: 'முகப்பு',
    aboutUs: 'எங்களைப் பற்றி',
    aboutHeader: 'வடு மடுவ பற்றி',
    aboutSub: '23 ஆண்டுகளுக்கும் மேலான அனுபவம் வாய்ந்த களுத்துறை தச்சு பட்டறை - மரக் கதவுகள், ஜன்னல்கள், நிலைகள், படிகள் மற்றும் சமையலறை அலமாரிகள்.',
    catalog: 'தச்சு பட்டியல்',
    services: 'சேவைகள்',
    gallery: 'கேலரி',
    contact: 'தொடர்புகொள்ள',
    customOrder: 'விருப்ப தச்சு ஆர்டர்',
    feedback: 'கருத்துகள்',
    requestQuote: 'விலை கேட்க',
    adminDesk: 'நிர்வாகி பகுதி',
    adminPortal: 'நிர்வாகி உள்நுழைவு',
    
    // Services List
    svcDoors: 'மரக் கதவுகள்',
    svcDoorsDesc: 'பிரதான கதவுகள், செதுக்கப்பட்ட தேக்கு கதவுகள் மற்றும் அறை கதவுகள்.',
    svcWindows: 'மர ஜன்னல்கள்',
    svcWindowsDesc: 'உயர்தர மர ஜன்னல்கள் மற்றும் சட்டங்கள்.',
    svcStaircases: 'மரப் படிகள் & கைகப்பிடிகள்',
    svcStaircasesDesc: 'தேக்கு மரப் படிகள் மற்றும் கைப்பிடிகள்.',
    svcPantry: 'சமையலறை அலமாரிகள்',
    svcPantryDesc: 'உங்கள் சமையலறைக்கான நவீன அலமாரிகள்.',
    svcDoorFrames: 'கதவு நிலைகள் (உளுவஹு)',
    svcDoorFramesDesc: '100% தரமான தேக்கு மற்றும் மகோகனி கதவு நிலைகள்.',
    svcCeilings: 'மர உச்சவரம்பு (Ceilings)',
    svcCeilingsDesc: 'அழகான மர உச்சவரம்புகள் மற்றும் பாலிஷ் பூச்சுகள்.',
    svcGeneralCarpentry: 'பொது தச்சு சேவைகள்',
    svcGeneralCarpentryDesc: 'பொருத்துதல், பழுதுபார்த்தல் மற்றும் கட்டிட மரவேலைகள்.',

    // Categories
    allCategories: 'அனைத்து தச்சு வேலைகள்',
    catDoors: 'மரக் கதவுகள்',
    catWindows: 'மர ஜன்னல்கள்',
    catStaircases: 'மரப் படிகள்',
    catPantry: 'சமையலறை அலமாரிகள்',
    catDoorFrames: 'கதவு நிலைகள்',
    catCeilings: 'மர உச்சவரம்பு',
    catGeneralCarpentry: 'தச்சு சேவைகள்',

    // Hero Slider
    heroBadge1: 'உயர்தர மரவேலைப்பாடு',
    heroTitle1_1: 'கைகளால் செய்யப்பட்ட',
    heroTitle1_2: 'தேக்கு பிரதான கதவுகள்',
    heroDesc1_1: '23 ஆண்டுகளுக்கும் மேலான அனுபவம் வாய்ந்த களுத்துறை தச்சு பட்டறை,',
    heroDesc1_2: 'தலைமுறைகள் கடந்து நிலைத்து நிற்கும் கதவுகள்.',
    heroBadge2: 'சமையலறை அலமாரிகள்',
    heroTitle2_1: 'உங்கள் வீட்டிற்கான',
    heroTitle2_2: 'சமையலறை அலமாரிகள்',
    heroDesc2_1: '100% உண்மையான இலங்கை தேக்கு மற்றும் மகோகனி மரத்தால் செய்யப்பட்டது,',
    heroDesc2_2: 'சிறந்த தச்சு வேலைப்பாடு.',
    heroBadge3: 'கட்டிட மரவேலைகள்',
    heroTitle3_1: 'நம்பகமான மரப் படிகள்',
    heroTitle3_2: 'மற்றும் உச்சவரம்புகள்',
    heroDesc3_1: 'உங்கள் வீட்டின்த்திற்கு ஏற்ப பிரத்யேகமாக வடிவமைக்கவும்.',
    heroDesc3_2: 'எங்கள் தச்சர்கள் மூலம் செய்து கொள்ளுங்கள்.',
    heroBadge4: 'உயர்தர தச்சு சேவைகள்',
    heroTitle4_1: 'சிறந்த மரவேலைப்பாடுகள்',
    heroTitle4_2: 'மற்றும் தயாரிப்புகள்',
    heroDesc4_1: 'உங்கள் வீட்டிற்கு ஏற்ற சிறந்த மரவேலைகள்',
    heroDesc4_2: 'நீடித்த தரம் மற்றும் அழகிய வடிவமைப்பு.',

    // Hero Quick Features
    getStarted: 'பட்டியலைப் பார்க்க',
    customOrderBtn: 'விருப்ப ஆர்டர்',
    expYears: '23+ ஆண்டுகள்',
    expSub: 'தச்சு அனுபவம்',
    premQuality: '100% தேக்கு',
    premSub: 'தரமான மரம்',
    customMade: 'விருப்ப வடிவமைப்பு',
    customSub: 'உங்கள் அளவிற்கு',
    ontimeDelivery: 'தீவு முழுதும்',
    ontimeSub: 'விநியோகம் & பொருத்துதல்',

    // Need Something Unique Banner
    needSomethingUnique: 'கதவுகள், ஜன்னல்கள் அல்லது அலமாரிகள் வேண்டுமா?',
    designIn3D: 'மர வகை, அளவுக்கு ஏற்ப தோராயமான விலையை அறியுங்கள்',
    designNow: 'இப்போதே ஆர்டர் செய்க',

    // Catalog Page
    catalogTitle: 'தச்சு பட்டியல்',
    catalogSubtitle: 'எங்கள் கதவுகள், ஜன்னல்கள், நிலைகள், படிகள் மற்றும் சமையலறை அலமாரிகள்',
    searchPlaceholder: 'கதவு, ஜன்னல், படிகள், அலமாரி, நிலை தேடுங்கள்...',
    sortBy: 'வரிசைப்படுத்து:',
    priceLowHigh: 'விலை: குறைந்ததிலிருந்து',
    priceHighLow: 'விலை: அதிகத்திலிருந்து',
    nameAZ: 'பெயர்: A முதல் Z',
    categories: 'வகைகள்',
    allProducts: 'அனைத்தும்',
    noProductsFound: 'எதுவும் கிடைக்கவில்லை.',
    inStock: 'கிடைக்கிறது / ஆர்டர் செய்யலாம்',
    estimatedPrice: 'மதிப்பிடப்பட்ட விலை',
    inquireQuote: 'விசாரிக்க / Quote',

    // Services Page
    servicesTitle: 'எங்கள் தச்சு சேவைகள்',
    servicesSubtitle: 'கதவுகள், ஜன்னல்கள், நிலைகள், படிகள் மற்றும் சமையலறை அலமாரி சேவைகள்',
    inquireNow: 'இப்போதே விசாரிக்க',

    // Gallery Page
    galleryTitle: 'படைப்புகள் கேலரி',
    gallerySubtitle: 'நாங்கள் பொறுத்திய கதவுகள், ஜன்னல்கள் மற்றும் சமையலறை அலமாரிகள்',
    all: 'அனைத்தும்',
    view: 'பார்க்க',
    viewMorePhotos: 'மேலும் படங்களை பார்க்க',

    // Contact Page
    contactTitle: 'எங்களை தொடர்பு கொள்ள',
    contactSubtitle: 'உங்கள் அனைத்து தச்சு தேவைகளுக்கும் உதவ நாங்கள் தயார்',
    address: 'முகவரி',
    addressValue: 'ரெண்டபல, தொடங்கொட, களுத்துறை, இலங்கை',
    openInMaps: 'Google Maps இல் பார்க்க',
    phoneWhatsapp: 'தொலைபேசி / WhatsApp',
    email: 'மின்னஞ்சல்',
    workingHours: 'வேலை நேரம்',
    workingHoursValue: 'திங்கள் - சனி : காலை 8:00 - மாலை 6:00',
    sundayClosed: 'ஞாயிறு : விடுமுறை',
    workshopLocation: 'பட்டறை அமைவிடம்',
    sendMessage: 'செய்தி அனுப்பவும்',
    yourName: 'உங்கள் முழு பெயர் *',
    phoneNumber: 'தொலைபேசி எண் *',
    emailAddress: 'மின்னஞ்சல்',
    projectDetails: 'தேவைகள் / விவரங்கள் *',
    submitBtn: 'விசாரணையை அனுப்பவும்',
    submitting: 'அனுப்பப்படுகிறது...',
    messageSentSuccess: 'நன்றி! உங்கள் விசாரணை வெற்றிகரமாக அனுப்பப்பட்டது. விரைவில் தொடர்பு கொள்வோம்.',

    // Custom Order Page
    customOrderHeader: 'விருப்ப தச்சு ஆர்டர் செய்க',
    customOrderSub: 'கதவுகள், ஜன்னல்கள், படிகள் அல்லது அலமாரிகளுக்கு மர வகை மற்றும் அளவை தேர்வு செய்க.',
    step1: '1. பொருள் மற்றும் மரத்தை தேர்வு செய்க',
    step2: '2. அளவுகள் மற்றும் புகைப்படங்கள்',
    step3: '3. உங்கள் விவரங்கள் & அனுப்புதல்',
    selectFurniture: 'தச்சு பொருளை தேர்ந்தெடுக்கவும்',
    selectWood: 'மர வகையை தேர்ந்தெடுக்கவும்',
    selectFinish: 'பாலிஷ் வகையை தேர்ந்தெடுக்கவும்',
    setDimensions: 'அளவுகள்',
    lengthCm: 'உயரம் / நீளம் (cm)',
    widthCm: 'அகலம் (cm)',
    heightCm: 'ஆழம் / தடிමන් (cm)',
    referencePhotos: 'புகைப்படங்களை பதிவேற்றவும்',
    uploadPhoto: 'படத்தை சேர்',
    remove: 'நீக்கு',
    customerInformation: 'உங்கள் தொடர்பு விவரங்கள்',
    fullName: 'முழு பெயர் *',
    addressField: 'முகவரி *',
    districtField: 'மாவட்டம் *',
    selectDistrict: 'மாவட்டத்தை தேர்ந்தெடுக்கவும்',
    phoneField: 'தொலைபேசி எண் (WhatsApp) *',
    notesField: 'கூடுதல் குறிப்புகள்',
    estimatedPriceTitle: 'மதிப்பிடப்பட்ட விலை',
    disclaimerNote: 'குறிப்பு: இது தோராயமான மதிப்பீடு மட்டுமே. இறுதி விலை அளவீடுகளுக்கு பின் முடிவு செய்யப்படும்.',
    submitOrderWhatsApp: 'WhatsApp வழியே அனுப்புக',
    orderSuccessModalTitle: 'ஆர்டர் அனுப்பப்பட்டது!',
    orderSuccessModalSub: 'உங்கள் ஆர்டர் விவரங்கள் WhatsApp வழியே எங்கள் தச்சருக்கு அனுப்பப்பட்டது.',
    closeModal: 'மூடுக',

    // Trust & Proof Section
    guaranteedTimberStandard: 'உத்தரவாதம் அளிக்கப்பட்ட மரம்',
    whyTrustUsTitle: '1,200+ குடும்பங்கள் எங்களை நம்புவது ஏன்?',
    trustDesc: 'நாங்கள் போலி மரங்களை பயன்படுத்துவதில்லை. அனைத்து கதவுகள், ஜன்னல்கள் மற்றும் நிலைகள் 100% இலங்க மரங்களால் செய்யப்படுகின்றன.',
    timberGuaranteesTitle: 'மர வகைகளுக்கான உத்தரவாதம்',
    fiveStepProcessTitle: '5-படி உற்பத்தி செயல்முறை',
    step1Title: 'அளவீடு மற்றும் யோசனை',
    step1Desc: 'உங்கள் புகைப்படத்தை அனுப்புங்கள். நாங்கள் இலவசமாக அளவெடுக்க வருகிறோம்.',
    step2Title: 'மர தேர்வு',
    step2Desc: '100% தரமான தேக்கு அல்லது மகோகனி மரத்தை தேர்வு செய்யுங்கள்.',
    step3Title: 'கைவினை வேலைப்பாடு',
    step3Desc: 'எங்கள் அனுபவம் வாய்ந்த தச்சர்கள் நுணுக்கமாக வடிவமைக்கிறார்கள்.',
    step4Title: 'PU பாலிஷ்',
    step4Desc: '5-அடுக்கு பாதுகாப்பு PU பாலிஷ் பூச்சு.',
    step5Title: 'விநியோகம் & பொருத்துதல்',
    step5Desc: 'பாதுகாப்பான விநியோகம் மற்றும் தொழில்முறை பொருத்துதல்.',
    clientReviewsTitle: 'வாடிக்கையாளர் கருத்துகள்',

    // Footer
    footerDesc: 'இலங்கையின் நம்பிக்கையான தச்சு பட்டறை. தேக்கு கதவுகள், ஜன்னல்கள், நிலைகள், படிகள் மற்றும் சமையலறை அலமாரிகள் தீவு முழுவதும்.',
    quickLinks: 'விரைவு இணைப்புகள்',
    ourServices: 'எங்கள் சேவைகள்',
    contactInfo: 'தொடர்பு விவரங்கள்',
    allRightsReserved: '© 2026 வඩු මඩුව (Wadu Maduwa). அனைத்து உரிமைகளும் பாதுகாக்கப்பட்டவை.',
    designedForCraftsmanship: 'இலங்கை தச்சு கலை பெருமை',

    // Feedback Page
    feedbackTitle: 'வாடிக்கையாளர் கருத்துகள்',
    feedbackSubtitle: 'எங்கள் தச்சு சேவை மற்றும் தரம் பற்றிய வாடிக்கையாளர்களின் அனுபவங்கள்',
    leaveReview: 'உங்கள் கருத்தை பகிரவும்',
    rating: 'மதிப்பீடு',
    submitReview: 'சமர்ப்பிக்கவும்',

    // Admin
    adminLoginTitle: 'நிர்வாகி உள்நுழைவு',
    username: 'பயனர் பெயர்',
    password: 'கடவுச்சொல்',
    signIn: 'உள்நுழைக',
    totalRevenue: 'மொத்த வருமானம்',
    pendingBalance: 'நிலுவை தொகை',
    newInquiries: 'புதிய விசாரணைகள்',
    catalogItems: 'பொருட்கள் எண்ணிக்கை'
  }
};

const LanguageContext = createContext();

export function LanguageProvider({ children }) {
  const [lang, setLangState] = useState(() => {
    return localStorage.getItem('wadu_lang') || 'SI';
  });

  const setLang = (newLang) => {
    setLangState(newLang);
    localStorage.setItem('wadu_lang', newLang);
  };

  const t = (key) => {
    return translations[lang]?.[key] || translations['SI']?.[key] || translations['EN']?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
