import React, { createContext, useContext, useState } from 'react';

const translations = {
  EN: {
    brandName: 'වඩු මඩුව',
    brandTag: 'Carpentry Workshop',
    home: 'Home',
    catalog: 'Catalog',
    services: 'Services',
    gallery: 'Gallery',
    contact: 'Contact Us',
    customOrder: 'Custom Order',
    feedback: 'Reviews & Feedback',
    requestQuote: 'Request Quote',
    adminDesk: 'Admin Desk',
    adminPortal: 'Admin Portal',
    
    // Hero Slider
    heroBadge1: 'PREMIUM QUALITY WOODWORK',
    heroTitle1_1: 'Add Elegance To Your',
    heroTitle1_2: 'Dream Living Space',
    heroDesc1_1: 'Crafted with over 25 years of master carpentry excellence,',
    heroDesc1_2: 'bringing timeless solid wood furniture to your home.',
    heroBadge2: 'CUSTOM DINING COLLECTION',
    heroTitle2_1: 'Superior Handcrafted',
    heroTitle2_2: 'Teak Dining Tables',
    heroDesc2_1: '100% genuine Sri Lankan teak and mahogany timber,',
    heroDesc2_2: 'built to withstand generations of family gatherings.',
    heroBadge3: 'LUXURY BEDROOM FURNITURE',
    heroTitle3_1: 'Bespoke Wooden Beds',
    heroTitle3_2: '& Fitted Bedroom Sets',
    heroDesc3_1: 'Custom designed to your exact dimensions and aesthetic preferences.',
    heroDesc3_2: 'Visualize in 3D and order directly.',

    // Hero Quick Features
    getStarted: 'Explore Catalog',
    customOrderBtn: 'Custom Order',
    expYears: '25+ Years',
    expSub: 'Experience',
    premQuality: '100% Teak',
    premSub: 'Genuine Wood',
    customMade: 'Custom Made',
    customSub: 'For Your Space',
    ontimeDelivery: 'Islandwide',
    ontimeSub: 'Delivery',

    // Quick Categories Bar
    livingRoom: 'Living Room',
    livingRoomSub: 'Chairs & Sets',
    bedroom: 'Bedroom',
    bedroomSub: 'Beds & Wardrobes',
    diningRoom: 'Dining Room',
    diningRoomSub: 'Tables & Chairs',
    office: 'Office',
    officeSub: 'Executive Desks',
    doorsWindows: 'Doors & Frames',
    doorsWindowsSub: 'Teak Entrance',

    // Need Something Unique Banner
    needSomethingUnique: 'Have a Custom Design Idea?',
    designIn3D: 'Customize wood, size & estimate cost instantly',
    designNow: 'Design Now',

    // Catalog Page
    catalogTitle: 'Furniture Catalog',
    catalogSubtitle: 'Explore our handcrafted Sri Lankan solid wooden furniture collection',
    searchPlaceholder: 'Search beds, tables, doors, wardrobes...',
    sortBy: 'Sort by:',
    priceLowHigh: 'Price: Low to High',
    priceHighLow: 'Price: High to Low',
    nameAZ: 'Name: A to Z',
    categories: 'Categories',
    allProducts: 'All Products',
    noProductsFound: 'No products matched your search criteria.',
    inStock: 'In Stock / Custom Made',
    estimatedPrice: 'Estimated Price',
    inquireQuote: 'Inquire / Quote',

    // Services Page
    servicesTitle: 'Our Woodworking Services',
    servicesSubtitle: 'Master carpentry & architectural timber solutions by Wadu Maduwa',
    service1Title: 'Custom Furniture Design & Build',
    service1Desc: 'Unique & personalized furniture handcrafted to your exact specifications.',
    service2Title: 'Restoration & Repair',
    service2Desc: 'We restore antique and cherished wooden furniture with expert care.',
    service3Title: 'Architectural Woodwork',
    service3Desc: 'Bespoke doors, windows, ceiling panels & fitted pantry cabinetry.',
    service4Title: 'PU Polishing & Finishing',
    service4Desc: 'High durability polyurethane matte, gloss & natural wood grain finishes.',
    service5Title: 'On-site Installation',
    service5Desc: 'Safe islandwide transport and professional fitting by master carpenters.',
    inquireNow: 'Inquire Now',

    // Gallery Page
    galleryTitle: 'Project Gallery',
    gallerySubtitle: 'Browse our completed carpentry & custom furniture installation projects',
    all: 'All',
    view: 'View',
    viewMorePhotos: 'View More Photos',

    // Contact Page
    contactTitle: 'Contact Us',
    contactSubtitle: 'We are here to assist with your custom furniture & carpentry inquiries',
    address: 'Workshop Address',
    addressValue: 'Rendapala, Dodangoda, Kalutara, Sri Lanka',
    openInMaps: 'Open in Google Maps',
    phoneWhatsapp: 'Phone / WhatsApp',
    email: 'Email Inquiry',
    workingHours: 'Working Hours',
    workingHoursValue: 'Mon - Sat : 8:00 AM - 6:00 PM',
    sundayClosed: 'Sunday : Closed',
    workshopLocation: 'Workshop Location',
    sendMessage: 'Send Us a Message',
    yourName: 'Your Full Name *',
    phoneNumber: 'Phone Number *',
    emailAddress: 'Email Address',
    projectDetails: 'Project Requirements / Description *',
    submitBtn: 'Submit Inquiry',
    submitting: 'Submitting...',
    messageSentSuccess: 'Thank you! Your inquiry has been sent successfully. We will call you back shortly.',

    // Custom Order Page
    customOrderHeader: 'Design Your Custom Furniture',
    customOrderSub: 'Select wood, dimensions & finish. Upload Pinterest photos or sketches to get instant price estimates.',
    step1: '1. Select Furniture & Wood',
    step2: '2. Dimensions & Reference Photos',
    step3: '3. Customer Details & Submit',
    selectFurniture: 'Select Furniture Item',
    selectWood: 'Select Wood Species',
    selectFinish: 'Select Polish Finish',
    setDimensions: 'Dimensions & Measurements',
    lengthCm: 'Length (cm)',
    widthCm: 'Width (cm)',
    heightCm: 'Height (cm)',
    referencePhotos: 'Upload Reference Photos / Sketches',
    uploadPhoto: 'Upload Photo / Sketch',
    remove: 'Remove',
    customerInformation: 'Your Contact & Delivery Details',
    fullName: 'Full Name *',
    addressField: 'Delivery Address *',
    districtField: 'District *',
    selectDistrict: 'Select District',
    phoneField: 'Phone Number (WhatsApp) *',
    notesField: 'Special Requirements / Notes',
    estimatedPriceTitle: 'Estimated Guideline Price',
    disclaimerNote: 'Note: This is an estimated guideline price. The final cost will be confirmed after discussing exact measurements with our master carpenter.',
    submitOrderWhatsApp: 'Send Order via WhatsApp',
    orderSuccessModalTitle: 'Order Request Sent Successfully!',
    orderSuccessModalSub: 'Your custom order details have been formatted and sent to our master carpenter via WhatsApp.',
    closeModal: 'Close',

    // Trust & Proof Section
    guaranteedTimberStandard: 'Guaranteed Timber Standard',
    whyTrustUsTitle: 'Why 1,200+ Families Trust වඩු මඩුව',
    trustDesc: 'We do not use MDF or cheap composite boards. Every piece of furniture is crafted from genuine, seasoned Sri Lankan solid timber with structural warranty.',
    timberGuaranteesTitle: 'Seasoned Timber Guarantees',
    fiveStepProcessTitle: '5-Step Precision Carpentry Workflow',
    step1Title: 'Idea & Measurements',
    step1Desc: 'Share your sketch or Pinterest photo. We take exact site measurements for free.',
    step2Title: 'Timber Selection',
    step2Desc: 'Pick 100% seasoned Grade-A Teak or Mahogany inspected for zero sapwood.',
    step3Title: 'Master Hand-Carving',
    step3Desc: 'Our master craftsmen in Kalutara shape every curve with precision.',
    step4Title: 'PU Lacquer Polish',
    step4Desc: '5-layer protective sanding and matte/gloss polyurethane polish treatment.',
    step5Title: 'Delivery & Fitting',
    step5Desc: 'Safe islandwide transport and professional on-site installation by our team.',
    clientReviewsTitle: 'What Our Clients Say',

    // Footer
    footerDesc: 'Sri Lanka’s trusted master carpentry workshop. Delivering handcrafted teak, mahogany & custom wooden interiors nationwide.',
    quickLinks: 'Quick Links',
    ourServices: 'Our Services',
    contactInfo: 'Contact Info',
    allRightsReserved: '© 2026 Wadu Maduwa (වඩු මඩුව). All rights reserved.',
    designedForCraftsmanship: 'Handcrafted with Pride in Sri Lanka',

    // Feedback Page
    feedbackTitle: 'Customer Reviews & Feedback',
    feedbackSubtitle: 'See what our clients say about our master carpentry quality and service',
    leaveReview: 'Share Your Experience',
    rating: 'Rating',
    submitReview: 'Submit Review',

    // Admin & General
    adminLoginTitle: 'Admin Portal Login',
    username: 'Username',
    password: 'Password',
    signIn: 'Sign In To Dashboard',
    totalRevenue: 'Total Revenue',
    pendingBalance: 'Pending Balance',
    newInquiries: 'New Inquiries',
    catalogItems: 'Catalogue Items'
  },

  SI: {
    brandName: 'වඩු මඩුව',
    brandTag: 'වඩු කාර්මික ශිල්පාගාරය',
    home: 'මුල් පිටුව',
    catalog: 'භාණ්ඩ ලැයිස්තුව',
    services: 'සේවාවන්',
    gallery: 'ගැලරිය',
    contact: 'සම්බන්ධ වන්න',
    customOrder: 'අභිරුචි ඇණවුම්',
    feedback: 'පාරිභෝගික අදහස්',
    requestQuote: 'මිල ගණන් ලබාගන්න',
    adminDesk: 'ඇඩ්මින් පාලකය',
    adminPortal: 'ඇඩ්මින් පිවිසුම',
    
    // Hero Slider
    heroBadge1: 'විශිෂ්ට ලී වඩු ශිල්පය',
    heroTitle1_1: 'ඔබේ නිවසට',
    heroTitle1_2: 'වටිනාකමක් එකතු කරන්න',
    heroDesc1_1: 'අවුරුදු 25කට අධික පළපුරුද්ද සහිත වඩු මඩුව,',
    heroDesc1_2: 'ඔබේ සිහින ලී නිර්මාණය සැබෑ කරගැනීමට ඔබ සමඟයි.',
    heroBadge2: 'කෑම මේස එකතුව',
    heroTitle2_1: 'උසස් නිමාවෙන් යුත්',
    heroTitle2_2: 'තේක්ක කෑම මේස සෙට්',
    heroDesc2_1: '100% ස්වාභාවික තේක්ක සහ මහෝගනි ලීයෙන් නිමවන ලද',
    heroDesc2_2: 'කල්පවතින ශ්‍රී ලාංකීය වඩු නිර්මාණ.',
    heroBadge3: 'නිදන කාමර ගෘහ භාණ්ඩ',
    heroTitle3_1: 'විශ්වසනීය අභිරුචි',
    heroTitle3_2: 'ලී ඇඳන් සහ ගෘහ භාණ්ඩ',
    heroDesc3_1: 'ඔබේ කාමරයේ ඉඩකඩට සහ රුචිකත්වයට ගැළපෙන පරිදි',
    heroDesc3_2: '3D මගින් සකසා සාදාගන්න.',

    // Hero Quick Features
    getStarted: 'ලැයිස්තුව බලන්න',
    customOrderBtn: 'Custom Order',
    expYears: 'අවුරුදු 25+',
    expSub: 'පළපුරුද්ද',
    premQuality: '100% තේක්ක',
    premSub: 'පිරිසිදු ලී',
    customMade: 'අභිරුචි නිර්මාණ',
    customSub: 'ඔබගේ ඉඩකඩට',
    ontimeDelivery: 'දිවයින් පුරා',
    ontimeSub: 'බෙදාහැරීම',

    // Quick Categories Bar
    livingRoom: 'සාලයට',
    livingRoomSub: 'පුටු සහ සෙට්',
    bedroom: 'කාමරයට',
    bedroomSub: 'ඇඳන් සහ අල්මාරි',
    diningRoom: 'කෑම කාමරයට',
    diningRoomSub: 'මේස සහ පුටු',
    office: 'කාර්යාලයට',
    officeSub: 'ලිපිද්‍රව්‍ය මේස',
    doorsWindows: 'දොර / ජනෙල්',
    doorsWindowsSub: 'තේක්ක දොරවල්',

    // Need Something Unique Banner
    needSomethingUnique: 'ඔබගේම Design එකක් සදාගන්නද?',
    designIn3D: 'ලී වර්ගය, ප්‍රමාණය අනුව දළ මිල ගණන් ලබාගන්න',
    designNow: 'දැන්ම සාදාගන්න',

    // Catalog Page
    catalogTitle: 'ගෘහ භාණ්ඩ ලැයිස්තුව',
    catalogSubtitle: 'අපගේ උසස් ප්‍රමිතියෙන් යුත් ලී ගෘහ භාණ්ඩ එකතුව පරීක්ෂා කරන්න',
    searchPlaceholder: 'ඇඳ, මේසය, අල්මාරිය, දොරවල් සොයන්න...',
    sortBy: 'වර්ගීකරණය:',
    priceLowHigh: 'මිල: අඩු සිට වැඩි',
    priceHighLow: 'මිල: වැඩි සිට අඩු',
    nameAZ: 'නම: A සිට Z',
    categories: 'වර්ගීකරණයන්',
    allProducts: 'සියලුම භාණ්ඩ',
    noProductsFound: 'ඔබ සොයන භාණ්ඩ සොයාගත නොහැකි විය.',
    inStock: 'ඇණවුම් කළ හැක',
    estimatedPrice: 'අනුමාන මිල',
    inquireQuote: 'විමසන්න / Quote',

    // Services Page
    servicesTitle: 'අපගේ වඩු සේවාවන්',
    servicesSubtitle: 'වඩු මඩුව මගින් සැපයෙන විශිෂ්ටතම වඩු කාර්මික සේවාවන්',
    service1Title: 'අභිරුචි ගෘහ භාණ්ඩ නිර්මාණය',
    service1Desc: 'ඔබේ අවශ්‍යතාවයට ගැළපෙන පරිදි විශේෂිත ගෘහ භාණ්ඩ සෑදීම.',
    service2Title: 'ගෘහ භාණ්ඩ අලුත්වැඩියාව',
    service2Desc: 'පැරණි ලී භාණ්ඩ ආරක්ෂිතව සහ අලංකාර ලෙස ප්‍රතිසංස්කරණය කිරීම.',
    service3Title: 'ගොඩනැගිලි ලී වඩු ශිල්පය',
    service3Desc: 'ප්‍රධාන දොරවල්, ජනෙල්, සිවිලිම් සහ පැන්ට්‍රි කබඩ් සෑදීම.',
    service4Title: 'ලී ඔපදැමීම (Polishing)',
    service4Desc: 'උසස්ම ප්‍රමිතියේ PU පොලිෂ් සහ මැට්/ග්ලොස් නිමාවන්.',
    service5Title: 'ස්ථානීය සවිකිරීම්',
    service5Desc: 'දිවයින් පුරා සුරක්ෂිත ප්‍රවාහනය සහ පළපුරුදු වඩු ශිල්පීන්ගේ සවිකිරීම්.',
    inquireNow: 'දැන්ම විමසන්න',

    // Gallery Page
    galleryTitle: 'නිර්මාණ ගැලරිය',
    gallerySubtitle: 'අප විසින් නිමකර දෙන ලද සත්‍ය ව්‍යාපෘති ඡායාරූප',
    all: 'සියල්ල',
    view: 'බලන්න',
    viewMorePhotos: 'තවත් ඡායාරූප බලන්න',

    // Contact Page
    contactTitle: 'අප හා සම්බන්ධ වන්න',
    contactSubtitle: 'ඔබගේ සියලු ලී ගෘහ භාණ්ඩ අවශ්‍යතා සඳහා අප සූදානම්',
    address: 'ලිපිනය',
    addressValue: 'රෙන්ඩපල, දොඩංගොඩ, කළුතර, ශ්‍රී ලංකාව',
    openInMaps: 'Google Maps මගින් බලන්න',
    phoneWhatsapp: 'දුරකථන / WhatsApp',
    email: 'විද්‍යුත් තැපෑල',
    workingHours: 'වැඩකරන වේලාවන්',
    workingHoursValue: 'සඳුදා - සෙනසුරාදා : පෙ.ව 8:00 - ප.ව 6:00',
    sundayClosed: 'ඉරිදා : වසා ඇත',
    workshopLocation: 'වඩු මඩුව පිහිටීම',
    sendMessage: 'පණිවිඩයක් යොමු කරන්න',
    yourName: 'ඔබගේ සම්පූර්ණ නම *',
    phoneNumber: 'දුරකථන අංකය *',
    emailAddress: 'විද්‍යුත් තැපෑල',
    projectDetails: 'අවශ්‍යතාවය / විස්තරය *',
    submitBtn: 'විමසීම යොමු කරන්න',
    submitting: 'යොමු වෙමින් පවතී...',
    messageSentSuccess: 'ස්තූතියි! ඔබගේ විමසීම සාර්ථකව යොමු විය. අපි ළඟදීම ඔබට කථා කරන්නෙමු.',

    // Custom Order Page
    customOrderHeader: 'ඔබේ හිතේ තියෙන Idea එකට Design කරන්න',
    customOrderSub: 'ලී වර්ගය, ප්‍රමාණය සහ Finish එක තෝරන්න. ඡායාරූපයක් යොමු කර දළ මිල ගණන් ගන්න.',
    step1: '1. භාණ්ඩය සහ ලී වර්ගය තෝරන්න',
    step2: '2. ප්‍රමාණයන් සහ ඡායාරූප',
    step3: '3. ඔබගේ තොරතුරු සහ යොමු කිරීම',
    selectFurniture: 'ගෘහ භාණ්ඩ වර්ගය තෝරන්න',
    selectWood: 'ලී වර්ගය තෝරන්න',
    selectFinish: 'ලී Finish එක තෝරන්න',
    setDimensions: 'ප්‍රමාණය සහ මැනීම්',
    lengthCm: 'දිග (cm)',
    widthCm: 'පළල (cm)',
    heightCm: 'උස (cm)',
    referencePhotos: 'ඡායාරූප / Sketch යොමු කරන්න',
    uploadPhoto: 'ඡායාරූපය එක් කරන්න',
    remove: 'ඉවත් කරන්න',
    customerInformation: 'ඔබගේ තොරතුරු සහ ලිපිනය',
    fullName: 'සම්පූර්ණ නම *',
    addressField: 'ලිපිනය *',
    districtField: 'දිස්ත්‍රික්කය *',
    selectDistrict: 'දිස්ත්‍රික්කය තෝරන්න',
    phoneField: 'දුරකථන අංකය (WhatsApp) *',
    notesField: 'විශේෂ සටහන්',
    estimatedPriceTitle: 'අනුමාන දළ මිල ගණන්',
    disclaimerNote: 'සැලකිය යුතුයි: මෙය දළ තක්සේරු මිලක් පමණි. අවසන් මිල මැනීම් පරීක්ෂාවෙන් පසු තීරණය වේ.',
    submitOrderWhatsApp: 'WhatsApp හරහා Order එක යොමු කරන්න',
    orderSuccessModalTitle: 'ඇණවුම සාර්ථකව යොමු විය!',
    orderSuccessModalSub: 'ඔබගේ අභිරුචි ඇණවුම් විස්තර WhatsApp හරහා අපගේ ශිල්පීන් වෙත යොමු කරන ලදී.',
    closeModal: 'වසා දමන්න',

    // Trust & Proof Section
    guaranteedTimberStandard: 'පිරිසිදු ලී සහතිකය',
    whyTrustUsTitle: '1200+ පාරිභෝගිකයින් වඩු මඩුව විශ්වාස කරන්නේ ඇයි?',
    trustDesc: 'අප MDF හෝ බාල ලෑලි භාවිත නොකරමු. සියලුම ගෘහ භාණ්ඩ පදම් කළ 100% සත්‍ය ශ්‍රී ලාංකීය ලීයෙන් සාදනු ලැබේ.',
    timberGuaranteesTitle: 'ලී වර්ග සඳහා වගකීම',
    fiveStepProcessTitle: 'වඩු මඩුවේ 5-පියවරේ නිෂ්පාදන ක්‍රියාවලිය',
    step1Title: 'අදහස සහ මැනීම්',
    step1Desc: 'ඔබගේ ඡායාරූපය ලබාදෙන්න. අපි නොමිලේ පැමිණ මැනීම් ලබාගන්නෙමු.',
    step2Title: 'ලී වර්ගය තේරීම',
    step2Desc: 'පදම් කළ 100% Grade-A තේක්ක හෝ මහෝගනි ලී පරීක්ෂා කර තෝරාගන්න.',
    step3Title: 'හස්ත කර්මාන්ත කැටයම්',
    step3Desc: 'කළුතර අපගේ පළපුරුදු වඩු ශිල්පීන් විසින් සියුම් ලෙස නිර්මාණය කරයි.',
    step4Title: 'PU පොලිෂ් නිමාව',
    step4Desc: '5-ස්තර ආරක්ෂිත PU පොලිෂ් සහ මැට්/ග්ලොස් නිමාව.',
    step5Title: 'බෙදාහැරීම සහ සවිකිරීම',
    step5Desc: 'දිවයින් පුරා සුරක්ෂිත ප්‍රවාහනය සහ වෘත්තීය සවිකිරීම.',
    clientReviewsTitle: 'පාරිභෝගික අදහස්',

    // Footer
    footerDesc: 'ශ්‍රී ලංකාවේ විශ්වාසනීයම වඩු ශිල්පාගාරය. තේක්ක, මහෝගනි සහ අභිරුචි ලී නිර්මාණ දිවයින් පුරා.',
    quickLinks: 'ඉක්මන් ලින්ක්',
    ourServices: 'අපගේ සේවාවන්',
    contactInfo: 'සම්බන්ධතා',
    allRightsReserved: '© 2026 වඩු මඩුව (Wadu Maduwa). සියලුම හිමිකම් ඇවිරිණි.',
    designedForCraftsmanship: 'ශ්‍රී ලාංකීය හස්ත කර්මාන්තයේ අභිමානය',

    // Feedback Page
    feedbackTitle: 'පාරිභෝගික අදහස් සහ ප්‍රතිචාර',
    feedbackSubtitle: 'අපගේ සේවාව සහ ලී නිමාව පිළිබඳව පාරිභෝගික අත්දැකීම්',
    leaveReview: 'ඔබගේ අදහස පළ කරන්න',
    rating: 'තරු ප්‍රමාණය',
    submitReview: 'යොමු කරන්න',

    // Admin & General
    adminLoginTitle: 'ඇඩ්මින් පිවිසුම',
    username: 'පරිශීලක නාමය',
    password: 'මුරපදය',
    signIn: 'ඇතුළු වන්න',
    totalRevenue: 'මුළු ආදායම',
    pendingBalance: 'ලැබීමට ඇති මුදල්',
    newInquiries: 'නව විමසීම්',
    catalogItems: 'භාණ්ඩ ප්‍රමාණය'
  },

  TA: {
    brandName: 'வடு மடுவ',
    brandTag: 'தச்சு பட்டறை',
    home: 'முகப்பு',
    catalog: 'தளபாடங்கள்',
    services: 'சேவைகள்',
    gallery: 'கேலரி',
    contact: 'தொடர்புகொள்ள',
    customOrder: 'விருப்ப ஆர்டர்',
    feedback: 'கருத்துகள்',
    requestQuote: 'விலை கேட்க',
    adminDesk: 'நிர்வாகி பகுதி',
    adminPortal: 'நிர்வாகி உள்நுழைவு',
    
    // Hero Slider
    heroBadge1: 'உயர்தர மரவேலைப்பாடு',
    heroTitle1_1: 'உங்கள் வீட்டிற்கு',
    heroTitle1_2: 'அழக சேர்க்கவும்',
    heroDesc1_1: '25 ஆண்டுகளுக்கும் மேலான அனுபவம் வாய்ந்த தச்சு பட்டறை,',
    heroDesc1_2: 'உங்கள் கனவு மர தளபாடங்களை உருவாக்க நாங்கள தயார்.',
    heroBadge2: 'சாப்பாட்டு மேஜை தொகுப்பு',
    heroTitle2_1: 'சிறந்த கைவினைப்',
    heroTitle2_2: 'தேக்கு சாப்பாட்டு மேசைகள்',
    heroDesc2_1: '100% உண்மையான இலங்கை தேக்கு மற்றும் மகோகனி மரத்தால் செய்யப்பட்டது,',
    heroDesc2_2: 'தலைமுறைகள் கடந்து நிலைத்து நிற்கும்.',
    heroBadge3: 'படுக்கையறை தளபாடங்கள்',
    heroTitle3_1: 'நம்பகமான விருப்பத்',
    heroTitle3_2: 'தேக்கு கட்டில்கள் & தளபாடங்கள்',
    heroDesc3_1: 'உங்கள் அறையின் அளவிற்கு ஏற்ப பிரத்யேகமாக வடிவமைக்கவும்.',
    heroDesc3_2: '3D மூலம் பார்த்து நேரடியாக ஆர்டர் செய்யுங்கள்.',

    // Hero Quick Features
    getStarted: 'பட்டியலைப் பார்க்க',
    customOrderBtn: 'விருப்ப ஆர்டர்',
    expYears: '25+ ஆண்டுகள்',
    expSub: 'அனுபவம்',
    premQuality: '100% தேக்கு',
    premSub: 'உண்மையான மரம்',
    customMade: 'விருப்ப வடிவமைப்பு',
    customSub: 'உங்கள் அளவிற்கு',
    ontimeDelivery: 'தீவு முழுதும்',
    ontimeSub: 'விநியோகம்',

    // Quick Categories Bar
    livingRoom: 'வரவேற்பறை',
    livingRoomSub: 'நாற்காலிகள்',
    bedroom: 'படுக்கையறை',
    bedroomSub: 'கட்டில்கள் & அலமாரிகள்',
    diningRoom: 'சாப்பாட்டு அறை',
    diningRoomSub: 'மேசைகள்',
    office: 'அலுவலகம்',
    officeSub: 'அலுவலக மேசைகள்',
    doorsWindows: 'கதவுகள் & ஜன்னல்கள்',
    doorsWindowsSub: 'தேக்கு கதவுகள்',

    // Need Something Unique Banner
    needSomethingUnique: 'சொந்த யோசனையில் தளபாடங்கள் செய்ய வேண்டுமா?',
    designIn3D: 'மர வகை, அளவுக்கு ஏற்ப தோராயமான விலையை உடனடியாக கணக்கிடுங்கள்',
    designNow: 'இப்போதே வடிவமைக்கவும்',

    // Catalog Page
    catalogTitle: 'தளபாடங்கள் பட்டியல்',
    catalogSubtitle: 'எங்கள் உயர்தர மர தளபாடங்களின் முழு பட்டியலையும் பாருங்கள்',
    searchPlaceholder: 'கட்டில், மேஜை, அலமாரி, கதவு தேடுங்கள்...',
    sortBy: 'வரிசைப்படுத்து:',
    priceLowHigh: 'விலை: குறைந்ததிலிருந்து',
    priceHighLow: 'விலை: அதிகத்திலிருந்து',
    nameAZ: 'பெயர்: A முதல் Z',
    categories: 'வகைகள்',
    allProducts: 'அனைத்து பொருட்கள்',
    noProductsFound: 'நீங்கள் தேடிய பொருட்கள் எதுவும் கிடைக்கவில்லை.',
    inStock: 'கிடைக்கிறது / ஆர்டர் செய்யலாம்',
    estimatedPrice: 'மதிப்பிடப்பட்ட விலை',
    inquireQuote: 'விசாரிக்க / Quote',

    // Services Page
    servicesTitle: 'எங்கள் தச்சு சேவைகள்',
    servicesSubtitle: 'வடு மடுவா வழங்கும் உயர்தர மரவேலை சேவைகள்',
    service1Title: 'விருப்ப தளபாட வடிவமைப்பு',
    service1Desc: 'உங்கள் தேவைக்கேற்ப பிரத்யேகமாக தளபாடங்கள் தயாரித்தல்.',
    service2Title: 'தளபாடங்கள் பழுதுபார்த்தல்',
    service2Desc: 'பழைய மர தளபாடங்களை கவனமாக புதுப்பித்தல்.',
    service3Title: 'கட்டிட மரவேலைகள்',
    service3Desc: 'முக்கிய கதவுகள், ஜன்னல்கள் மற்றும் சமையலறை அலமாரிகள்.',
    service4Title: 'மர பாலிஷ் (Polishing)',
    service4Desc: 'உயர்தர PU பாலிஷ் மற்றும் மேட்/கிளாஸ் ஃபினிஷிங்.',
    service5Title: 'இடத்தில பொருத்துதல்',
    service5Desc: 'பாதுகாப்பான போக்குவரத்து மற்றும் சிறந்த தச்சர்களின் பொருத்தும் சேவை.',
    inquireNow: 'இப்போதே விசாரிக்க',

    // Gallery Page
    galleryTitle: 'படைப்புகள் கேலரி',
    gallerySubtitle: 'நாங்கள் செய்து முடித்த உண்மை திட்டங்களின் புகைப்படங்கள்',
    all: 'அனைத்தும்',
    view: 'பார்க்க',
    viewMorePhotos: 'மேலும் படங்களை பார்க்க',

    // Contact Page
    contactTitle: 'எங்களை தொடர்பு கொள்ள',
    contactSubtitle: 'உங்கள் அனைத்து தளபாட தேவைகளுக்கும் உதவ நாங்கள் தயார்',
    address: 'முகவரி',
    addressValue: 'ரெண்டபல, தொடங்கொட, களுத்துறை, இலங்கை',
    openInMaps: 'Google Maps இல் பார்க்க',
    phoneWhatsapp: 'தொலைபேசி / WhatsApp',
    email: 'மின்னஞ்சல்',
    workingHours: 'வேலை நேரம்',
    workingHoursValue: 'திங்கள் - சனி : காலை 8:00 - மாலை 6:00',
    sundayClosed: 'ஞாயிறு : விடுமுறை',
    workshopLocation: 'பட்டறை அமைவிடம்',
    sendMessage: 'செய்தி அனுப்பவும்',
    yourName: 'உங்கள் முழு பெயர் *',
    phoneNumber: 'தொலைபேசி எண் *',
    emailAddress: 'மின்னஞ்சல்',
    projectDetails: 'தேவைகள் / விவரங்கள் *',
    submitBtn: 'விசாரணையை அனுப்பவும்',
    submitting: 'அனுப்பப்படுகிறது...',
    messageSentSuccess: 'நன்றி! உங்கள் விசாரணை வெற்றிகரமாக அனுப்பப்பட்டது. விரைவில் தொடர்பு கொள்வோம்.',

    // Custom Order Page
    customOrderHeader: 'உங்கள் சொந்த யோசனையில் ஆர்டர் செய்யுங்கள்',
    customOrderSub: 'மர வகை, அளவு மற்றும் பாலிஷ் தேர்ந்தெடுக்கவும். புகைப்படத்தை பதிவேற்றி மதிப்பீட்டை பெறுங்கள்.',
    step1: '1. பொருள் மற்றும் மரத்தை தேர்வு செய்க',
    step2: '2. அளவுகள் மற்றும் புகைப்படங்கள்',
    step3: '3. உங்கள் விவரங்கள் & அனுப்புதல்',
    selectFurniture: 'பொருளை தேர்ந்தெடுக்கவும்',
    selectWood: 'மர வகையை தேர்ந்தெடுக்கவும்',
    selectFinish: 'பாலிஷ் வகையை தேர்ந்தெடுக்கவும்',
    setDimensions: 'அளவுகள்',
    lengthCm: 'நீளம் (cm)',
    widthCm: 'அகலம் (cm)',
    heightCm: 'உயரம் (cm)',
    referencePhotos: 'புகைப்படங்களை பதிவேற்றவும்',
    uploadPhoto: 'படத்தை சேர்',
    remove: 'நீக்கு',
    customerInformation: 'உங்கள் தொடர்பு விவரங்கள்',
    fullName: 'முழு பெயர் *',
    addressField: 'முகவரி *',
    districtField: 'மாவட்டம் *',
    selectDistrict: 'மாவட்டத்தை தேர்ந்தெடுக்கவும்',
    phoneField: 'தொலைபேசி எண் (WhatsApp) *',
    notesField: 'கூடுதல் குறிப்புகள்',
    estimatedPriceTitle: 'மதிப்பிடப்பட்ட விலை',
    disclaimerNote: 'குறிப்பு: இது தோராயமான மதிப்பீடு மட்டுமே. இறுதி விலை அளவீடுகளுக்கு பின் முடிவு செய்யப்படும்.',
    submitOrderWhatsApp: 'WhatsApp வழியே அனுப்புக',
    orderSuccessModalTitle: 'ஆர்டர் அனுப்பப்பட்டது!',
    orderSuccessModalSub: 'உங்கள் ஆர்டர் விவரங்கள் WhatsApp வழியே எங்கள் தச்சருக்கு அனுப்பப்பட்டது.',
    closeModal: 'மூடுக',

    // Trust & Proof Section
    guaranteedTimberStandard: 'உத்தரவாதம் அளிக்கப்பட்ட மரம்',
    whyTrustUsTitle: '1,200+ குடும்பங்கள் எங்களை நம்புவது ஏன்?',
    trustDesc: 'நாங்கள் போலி மரங்களை பயன்படுத்துவதில்லை. அனைத்து தளபாடங்களும் 100% தரமான இலங்கை மரங்களால் செய்யப்படுகின்றன.',
    timberGuaranteesTitle: 'மர வகைகளுக்கான உத்தரவாதம்',
    fiveStepProcessTitle: '5-படி உற்பத்தி செயல்முறை',
    step1Title: 'யோசனை மற்றும் அளவீடு',
    step1Desc: 'உங்கள் புகைப்படத்தை அனுப்புங்கள். நாங்கள் இலவசமாக அளவெடுக்க வருகிறோம்.',
    step2Title: 'மர தேர்வு',
    step2Desc: '100% தரமான தேக்கு அல்லது மகோகனி மரத்தை தேர்வு செய்யுங்கள்.',
    step3Title: 'கைவினை வேலைப்பாடு',
    step3Desc: 'எங்கள் அனுபவம் வாய்ந்த தச்சர்கள் நுணுக்கமாக வடிவமைக்கிறார்கள்.',
    step4Title: 'PU பாலிஷ்',
    step4Desc: '5-அடுக்கு பாதுகாப்பு PU பாலிஷ் பூச்சு.',
    step5Title: 'விநியோகம் & பொருத்துதல்',
    step5Desc: 'பாதுகாப்பான விநியோகம் மற்றும் தொழில்முறை பொருத்துதல்.',
    clientReviewsTitle: 'வாடிக்கையாளர் கருத்துகள்',

    // Footer
    footerDesc: 'இலங்கையின் நம்பிக்கையான தச்சு பட்டறை. தேக்கு, மகோகனி மற்றும் விருப்ப மர தளபாடங்கள் தீவு முழுவதும்.',
    quickLinks: 'விரைவு இணைப்புகள்',
    ourServices: 'எங்கள் சேவைகள்',
    contactInfo: 'தொடர்பு விவரங்கள்',
    allRightsReserved: '© 2026 வடு மடுவ (Wadu Maduwa). அனைத்து உரிமைகளும் பாதுகாக்கப்பட்டவை.',
    designedForCraftsmanship: 'இலங்கை கைவினை பெருமை',

    // Feedback Page
    feedbackTitle: 'வாடிக்கையாளர் கருத்துகள்',
    feedbackSubtitle: 'எங்கள் சேவை மற்றும் தரம் பற்றிய வாடிக்கையாளர்களின் அனுபவங்கள்',
    leaveReview: 'உங்கள் கருத்தை பகிரவும்',
    rating: 'மதிப்பீடு',
    submitReview: 'சமர்ப்பிக்கவும்',

    // Admin & General
    adminLoginTitle: 'நிர்வாகி உள்நுழைவு',
    username: 'பயனர் பெயர்',
    password: 'கடவுச்சொல்',
    signIn: 'உள்நுழைக',
    totalRevenue: 'மொத்த வருமானம்',
    pendingBalance: 'நிலுவை தொகை',
    newInquiries: 'புதிய விசாரணைகள்',
    catalogItems: 'பொருட்கள் எண்ணிக்கை'
  }
};

const LanguageContext = createContext();

export function LanguageProvider({ children }) {
  const [lang, setLangState] = useState(() => {
    return localStorage.getItem('wadu_lang') || 'SI';
  });

  const setLang = (newLang) => {
    setLangState(newLang);
    localStorage.setItem('wadu_lang', newLang);
  };

  const t = (key) => {
    return translations[lang]?.[key] || translations['SI']?.[key] || translations['EN']?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
